version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Flexible API URL - works for localhost and remote servers
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - willowbank-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_PATH=/app/data/willowbank.db
      # Flexible CORS origin
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    networks:
      - willowbank-net
    restart: unless-stopped

volumes:
  node_modules_frontend:
  node_modules_backend:

networks:
  willowbank-net:
    driver: bridge

