version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - willowbank-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/willowbank.db
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - willowbank-net
    restart: unless-stopped

volumes:
  node_modules_frontend:
  node_modules_backend:

networks:
  willowbank-net:
    driver: bridge